# Generated by Django 6.0.3 on 2026-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='resimler/'),
        ),
    ]
