# Generated by Django 6.0.3 on 2026-04-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_ilan_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='fiyat',
        ),
        migrations.AddField(
            model_name='ilan',
            name='asansor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ilan',
            name='balkon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ilan',
            name='banyo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ilan',
            name='bina_yasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ilan',
            name='isitma',
            field=models.CharField(choices=[('dogalgaz', 'Doğalgaz'), ('kombi', 'Kombi'), ('merkezi', 'Merkezi'), ('klima', 'Klima'), ('soba', 'Soba')], default='dogalgaz', max_length=20),
        ),
        migrations.AddField(
            model_name='ilan',
            name='kat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ilan',
            name='metrekare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(default='1+1', max_length=10),
        ),
        migrations.AddField(
            model_name='ilan',
            name='site_aidati',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ilan',
            name='site_icinde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
    ]
