# Generated by Django 6.0.3 on 2026-04-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0003_remove_ilan_fiyat_ilan_asansor_ilan_balkon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilan',
            name='resim',
        ),
        migrations.AlterField(
            model_name='ilan',
            name='kat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IlanMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='medya/')),
                ('tip', models.CharField(choices=[('resim', 'Resim'), ('video', 'Video')], default='resim', max_length=10)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medyalar', to='ilanlar.ilan')),
            ],
        ),
    ]
