# Generated by Django 6.0.3 on 2026-04-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0005_ilan_kullanici_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='haberler/')),
                ('renk', models.CharField(default='#1a3a5c', max_length=20)),
                ('etiket', models.CharField(default='DUYURU', max_length=50)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.AlterField(
            model_name='ilanmedya',
            name='dosya',
            field=models.ImageField(upload_to='medya/'),
        ),
    ]
