# Generated by Django 6.0.3 on 2026-04-25 08:30

import django.db.models.deletion
import ilanlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0008_haber_icerik'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkademiKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Akademi Kategorisi',
                'verbose_name_plural': 'Akademi Kategorileri',
                'ordering': ['sira'],
            },
        ),
        migrations.AlterField(
            model_name='hutbe',
            name='normal_pdf',
            field=models.FileField(storage=ilanlar.models.InlinePDFStorage(), upload_to='hutbeler/'),
        ),
        migrations.AlterField(
            model_name='hutbe',
            name='telefon_pdf',
            field=models.FileField(storage=ilanlar.models.InlinePDFStorage(), upload_to='hutbeler/'),
        ),
        migrations.CreateModel(
            name='Akademi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('sehir', models.CharField(blank=True, max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('resmi_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('konum_url', models.URLField(blank=True, help_text='Google Maps adres linki')),
                ('sira', models.IntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akademiler', to='ilanlar.akademikategori')),
            ],
            options={
                'verbose_name': 'Akademi',
                'verbose_name_plural': 'Akademiler',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='AkademiResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='akademi/')),
                ('sira', models.IntegerField(default=0)),
                ('akademi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='ilanlar.akademi')),
            ],
            options={
                'verbose_name': 'Akademi Resmi',
                'verbose_name_plural': 'Akademi Resimleri',
                'ordering': ['sira'],
            },
        ),
    ]
