# Generated by Django 6.0.3 on 2026-04-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0009_akademikategori_alter_hutbe_normal_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkademiGorevli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('unvan', models.CharField(choices=[('mudur', 'Merkez Müdürü'), ('mudur_yardimcisi', 'Müdür Yardımcısı'), ('egitim_gorevlisi', 'Eğitim Görevlisi')], default='egitim_gorevlisi', max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gorevliler/')),
                ('biyografi', models.TextField(blank=True)),
                ('egitim', models.TextField(blank=True, help_text='Her satıra bir eğitim bilgisi yaz')),
                ('uzmanlik', models.CharField(blank=True, help_text='Virgülle ayır: Tecvid, Kıraat, Hadis', max_length=300)),
                ('deneyim_yil', models.IntegerField(default=0)),
                ('mezun_ogrenci', models.IntegerField(default=0)),
                ('sira', models.IntegerField(default=0)),
                ('akademi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevliler', to='ilanlar.akademi')),
            ],
            options={
                'verbose_name': 'Akademi Görevlisi',
                'verbose_name_plural': 'Akademi Görevlileri',
                'ordering': ['sira'],
            },
        ),
    ]
