# Generated by Django 6.0.3 on 2026-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0010_akademigorevli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200)),
                ('mesaj', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-tarih'],
            },
        ),
    ]
