# Generated by Django 6.0.3 on 2026-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0011_bildirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='onaylandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='haber',
            name='onaylandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ilan',
            name='onaylandi',
            field=models.BooleanField(default=False),
        ),
    ]
