# Generated by Django 6.0.3 on 2026-04-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0012_bildirim_onaylandi_haber_onaylandi_ilan_onaylandi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayBekleyenIlan',
            fields=[
            ],
            options={
                'verbose_name': 'Onay Bekleyen İlan',
                'verbose_name_plural': 'Onay Bekleyen İlanlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ilanlar.ilan',),
        ),
    ]
